= Get support for {astra_db}

This topic explains how to get support for your {company} {astra_db} database.

== Check the status of {astra_db}

Refer to the https://status.astra.datastax.com/[DataStax Astra DB Status page] to review all statuses including any major disruptions that impact the Astra system as a whole. 

== Subscribe to updates

Stay up-to-date by subscribing to the {astra_db} System. 

. Open https://status.astra.datastax.com
. Click **SUBSCRIBE TO UPDATES**. Select an option to receive the updates:

 * Email: Get email notifications whenever {astra_db} creates, updates or resolves an incident
 * Phone: Get text message notifications whenever {astra_db} creates or resolves an incident
 * Slack: Get incident updates and maintenance status messages in Slack
 * Webhook: Get webhook notifications whenever {astra_db} creates an incident, updates an incident, resolves an incident or changes a component status
. The *Subscriber* page appears. All individual component boxes are checked automatically. 
.. You can minimize the *Components* list using the down arrow next to each Component name. 
.. Optionally, click *Select none* to remove all checks from each box. 
. Review the options and check the box to select your choices. For example, if you only want to see results for the Astra Classic DB, check that box. If you do not want to see the results for AWS ec2-eu-west-1, uncheck that AWS region.
. Click *Subscribe* if this is your first subscription, or *Save* if making updates to your subscription.

//Add the appropriate information for your selection. Click **Subscribe** for your selection.

When your subscriptions are complete, a confirmation messages appears at the top of your screen. 

Scroll down the page to review any past incidents, which are separated by plan. For example, if you have both Serverless and Classic option, both Serverless and Classic past incidents appear on this page. 

[NOTE]
====
To receive Email/text messages, make sure the necessary settings are enabled. Text message subscriptions are only enabled for {astra_db} paid plans. You cannot configure these messages until you activate your database with a paid plan.
====

Optionally, click *View historical uptime* to see the number of incidents for a given month.

== Submit a support ticket
We want to provide as much support as possible. There are situations that are new and require our attention. Is the database functioning properly? Are you receiving an unrecognizable error? If an alert or incident is identified, submit a Support Ticket to inform us.
The Support Ticket allows us to not only learn about the new situation, but devise a plan for future users (if this happens again).

. Open {astra_db} and click **Help Center**. The Help Center panel opens with various links.
. Click **Submit a Ticket**.
. Required fields are marked with an asterisk.
. Add any attachment necessary to help describe your situation.
. When you are finished, click **Submit**.


== When to escalate a support ticket
Some situations are more critical than others and require direct attention. Examples of these situations include:

* A complete loss of service or you cannot continue with regular operations for an unknown reason
* Production systems have crashed
* Production system that is suspended indefinitely

For these situations set the **Priority** to **Urgent**.
If you prefer to speak with us, click **Live Chat**. We are ready to help. To help us better understand the issue, you can add an attachment such as a GIF file.
