= What is {astra_db}?
:slug: what-is-datastax-astra

{company} {astra_db} is a {serverless_special} multi-cloud native DBaaS built on Apache Cassandra&reg;. 

Start today with a $300/year free credit. You can use the https://astra.datastax.com[{astra_ui}, window="_blank"] and APIs to greatly simplify cloud-native Cassandra application development. {astra_db} reduces deployment time from weeks to minutes, and delivers a combination of {serverless_special} pay-as-you-go pricing with the freedom and agility of multi-cloud and open-source software. All that functionality is yours without the hassles of complex database and infrastructure administration.

{astra_db} database guardrails and limits help enforce best practices by defining parameters for operations, such as table number and column size limits, ensuring the database operates with consistent performance and maintains cluster health.

[TIP]
====
In addition to this {astra_db} documentation, be sure to check out our new https://awesome-astra.github.io/docs/[Awesome-Astra, window="_blank"] site. It includes developer-focused tutorials and learning materials to help you quickly build great applications. Awesome-Astra also provides a rich set of external tools to connect your apps to Astra DB data, and "Try It!" features within the product's API docs. Get a jump on your learning and start coding today!
====

To learn more about {astra_db}, we recommend watching the https://www.youtube.com/playlist?list=PL2g2h-wyI4SpWK1G3UaxXhzZc6aUFXbvL[Astra DB videos, window="_blank"] on the DataStax Developers YouTube channel. Our developers introduce you to the most frequently used {astra_db} features. 

For introductory information about {astra_db}, start in our xref:astra-faq.adoc[{astra_db} FAQs, window="_blank"].

== {astra_stream}

For documentation about {astra_stream}, see https://docs.datastax.com/en/astra-streaming/docs/[{astra_stream}, window="_blank"].

ifeval::["{evalproduct}" == "DB Serverless"]
== {astra_db} Classic documentation

If you're a user of {astra_db} Classic, switch over to the https://docs.datastax.com/en/astra-classic/docs[documentation, window="_blank"] written specifically for it.
endif::[]

ifeval::["{evalproduct}" == "DB Classic"]
== {astra_db} Serverless documentation

If you're a user of {astra_db} Serverless, switch over to the https://docs.datastax.com/en/astra-serverless/docs[documentation, window="_blank"] written specifically for it.
endif::[]
