= Migrate C++ driver
:slug: migrating-your-datastax-c-driver-to-connect-with-astra-databases

Complete the following procedure to migrate your existing {company} C++ driver to a version that is capable of connecting to Astra databases created using {company} {astra_db}.

== Prerequisites
* xref:manage:db/managing-db.adoc#_create_your_database[Create a database] using https://astra.datastax.com/register[{astra_db}, window="_blank"].
* xref:connect:connecting.adoc#_downloading_secure_connect_bundle[Download the secure connect bundle] to obtain connection credentials for your {astra_db} database.
* Get your _Client ID_ and _Client Secret_ by creating your xref:manage:org/manage-tokens.adoc[application token] for your username and password.

+
include::partial$tip_invite_users_to_join_org.adoc[]

* Download the {company} C++ driver and dependency packages for your platform using the links in the following table:

=== {company} C++ driver download links
[cols=2*,options=header]
|===
|Platform
|Download links

|CentOS 6
|http://downloads.datastax.com/cpp-driver/centos/6/dse[Driver, window="_blank"] \| http://downloads.datastax.com/cpp-driver/centos/6/dependencies[Dependencies, window="_blank"]

|CentOS 7
|http://downloads.datastax.com/cpp-driver/centos/7/dse[Driver, window="_blank"] \| http://downloads.datastax.com/cpp-driver/centos/7/dependencies[Dependencies, window="_blank"]

|CentOS 8
|http://downloads.datastax.com/cpp-driver/centos/8/dse[Driver, window="_blank"] \| http://downloads.datastax.com/cpp-driver/centos/8/dependencies[Dependencies, window="_blank"]

|Ubuntu 14.04
|http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dse[Driver, window="_blank"] \| http://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies[Dependencies, window="_blank"]

|Ubuntu 16.04
|http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dse[Driver, window="_blank"] \| http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dependencies[Dependencies, window="_blank"]

|Ubuntu 18.04
|http://downloads.datastax.com/cpp-driver/ubuntu/18.04/dse[Driver, window="_blank"] \| http://downloads.datastax.com/cpp-driver/ubuntu/18.04/dependencies[Dependencies, window="_blank"]

|Windows
|http://downloads.datastax.com/cpp-driver/windows/dse[Driver, window="_blank"] \| http://downloads.datastax.com/cpp-driver/windows/dependencies[Dependencies, window="_blank"]

|===

Other platforms should build the driver from the link:https://github.com/datastax/cpp-driver[source code packages, window="_blank"].

* Using the packages you downloaded, follow the link:https://docs.datastax.com/en/developer/cpp-dse-driver/latest/installation/[installation instructions, window="_blank"] for your platform to install the {company} C++ driver.

== Procedure
. In your existing {company} C++ driver code, modify the connection code to use the {astra_db} API.
+
[NOTE]
====
Both the {company} C++ driver for Apache Cassandra and the {company} Enterprise (DSE) C++ driver use the same code to connect and query your Astra database.
When using the DSE C++ driver, use the header `#include <dse.h>`.
====
+
The `secure_connect_bundle` must include the absolute path to your Astra database credentials (`+secure-connect-**database_name**.zip+`).
+
[source,c++]
----
cass_cluster_set_credentials(cluster, "clientId", "clientSecret");

  CassFuture* connect_future = cass_session_connect(session, cluster);
  if (cass_future_error_code(connect_future) == CASS_OK) {
    * Use the session to run queries _
    }
  else {
    _ Handle error *
  }
----

. Build and link your application against the {company} C++ driver.
+
* *Linux or macOS*
+
[NOTE]
====
For static linking, use `cassandra_static.a` or `dse_static.a`.
====
+
[tabs]
====
{company} C++ driver for Apache Cassandra::
+
--
[source,c++]
----
cc connect-database.c -I/path/to/cassandra.h -L/path/to/cassandra.so -lcassandra
----
--
DSE C++ driver::
+
--
[source,c++]
----
cc connect-database.c -I/path/to/dse.h -L/path/to/dse.so -ldse
----
--
====
+
* **Windows**
Include these libraries in your Microsoft Visual Studio project by adding them to the project’s properties under ]``Configuration Properties/Linker/Input/Additional Dependencies``.
+
[NOTE]
====
For static linking, use ``cassandra_static.lib`` or ``dse_static.lib``pass:c[.
====

_{company} C++ driver for Apache Cassandra_
Link your application against ``cassandra.lib``.
Your application will also require ``cassandra.dll` to be in your runtime path.

_DSE C++ driver_
Link your application against `dse.lib`.
Your application will also require `dse.dll` to be in your runtime path.
