= DataStax Antora UI
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://github.com/riptano/antora-ui-docs
:url-preview: https://gitlab.com/antora/antora-ui-default
// External URLs:
:url-antora: https://antora.org
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-source-maps: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

This project houses the elements of a UI bundle that can be used by {url-antora}[Antora] to generate a documentation site. You can see a preview of the default UI at https://gitlab.com/antora/antora-ui-default.

DataStax has customized the UI with the changes that are located in this repository. 
The elements defined are: CSS, fonts, images, helper programs, Javascript elements, layouts, and Handlebar partials (*.hbs) that are used in the layouts.

== Using the UI in Antora playbooks to build a docset

The UI bundle is defined in an Antora playbook YAML file, and retrieved from the designated URL. 
All DataStax docsets use the UI bundle defined and built from this repository. 
Most repositories also have supplemental files, defined in `playbooks/supplemental_ui` in the doc repository, that override the defined UI bundle and provide specific banner images for each DataStax product.

To use the UI bundle built in this repository, add the following UI configuration to your playbook:

[source,yaml]
----
ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/raw/main/releases/download/v0.8/ui-bundle.zip
----

Read on to learn how to customize the UI for our documentation.

== Developing a new UI bundle

This section offers a basic tutorial to teach you how to set up the UI project, preview it locally, and bundle it for use with Antora.
A more comprehensive example can be found in the documentation at https://docs.antora.org.

=== Prerequisites

In order to build a bundle, you'll want to preview your changes, and then bundle them.
To do those steps, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* {url-nodejs}[Node.js] (commands: `node` and `npm`)
* {url-gulp}[Gulp CLI] (command: `gulp`)

==== git

First, make sure you have git installed.

 $ git --version

If not, {url-git-dl}[download and install] the git package for your system.

==== Node.js

Next, make sure that you have Node.js installed (which also provides npm).

 $ node --version

If this command fails with an error, you don't have Node.js installed.
If the command doesn't report an LTS version of Node.js (e.g., v10.15.3), it means you don't have a suitable version of Node.js installed.
In this guide, we'll be installing Node.js 16.

While you can install Node.js from the official packages, we strongly recommend that you use {url-nvm}[nvm] (Node Version Manager) to manage your Node.js installation(s).
Follow the {url-nvm-install}[nvm installation instructions] to set up nvm on your machine.

Once you've installed nvm, open a new terminal and install Node.js 16 using the following command:

 $ nvm install 16

You can switch to this version of Node.js at any time using the following command:

 $ nvm use 16

To make Node.js 16 the default in new terminals, type:

 $ nvm alias default 16

Now that you have Node.js installed, you can proceed with installing the Gulp CLI.

==== Gulp CLI

You'll need the Gulp command-line interface (CLI) to run the build.
The Gulp CLI package provides the `gulp` command which, in turn, executes the version of Gulp declared by the project.

You should install the Gulp CLI globally (which resolves to a location in your user directory if you're using nvm) using the following command:

 $ npm install -g gulp-cli

Verify the Gulp CLI is installed and on your PATH by running:

 $ gulp --version

Now that you have the prerequisites installed, you can fetch and build the UI project.

=== Clone and Initialize the UI Project

Clone the `github.com/riptano/antora-ui-docs` project using git:

[subs=attributes+]
 $ git clone {url-project} &&
   cd "`basename $_`"

The example above clones this repository and then switches to the project folder on your filesystem.
Stay in this project folder when executing all subsequent commands.

Use npm to install the project's dependencies inside the project.
In your terminal, execute the following command:

 $ npm install

This command installs the dependencies listed in [.path]_package.json_ into the [.path]_node_modules/_ folder inside the project.
This folder does not get included in the UI bundle and should _not_ be committed to the source control repository.

=== Preview the UI

The default UI project is configured to preview offline.
The files in the [.path]_preview-src/_ folder provide the sample content that allow you to see the UI in action.
In this folder, you'll primarily find pages written in AsciiDoc.
These pages provide a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command:

 $ gulp preview

You'll see a URL listed in the output of this command:

....
[12:00:00] Starting server...
[12:00:00] Server started http://localhost:5252
[12:00:00] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `preview:build` task if a change is detected, and sending the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

=== Package for Use with Antora

If you need to package the UI so you can use it to generate the documentation site locally, run the following command:

 $ gulp bundle

If any errors are reported by lint, you'll need to fix them.

When the command completes successfully, the UI bundle will be available at [.path]_build/ui-bundle.zip_.

Next, you'll need to create a new release following https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository[these instructions].
Be sure to include the [.path]_build/ui-bundle.zip_ file as a binary in the release.

If you have the preview running, and you want to bundle without causing the preview to be clobbered, use:

 $ gulp bundle:pack

The UI bundle will again be available at [.path]_build/ui-bundle.zip_.

=== Update documentation repository playbooks to use a new UI bundle

If you build a new UI bundle, all the DataStax docs repositories must be updated. 
The following steps must be completed in each doc repository:

. Create a PR branch for the work..
. Update all affected playbooks with an appropriate UI bundle url.
. Test if the UI is building correctly with a local build.
. Get PR approval and merge the PR to the appropriate branch (`main` for most repositories).
. Rebuild one updated playbook.
. Deploy to coppi to review the build to ensure the latest UI changes are working.
. Rebuild the documentation for all affected playbooks using the scripsi `bsys` command.
. Deploy to docs-preview and sync all docsets.

== Copyright and License

Copyright (C) 2017-2020 OpenDevise Inc., the Antora Project, and DataStax, Inc.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

Development of Antora is led and sponsored by {url-opendevise}[OpenDevise Inc].

In addition, this repository has been modified by the DataStax Documentation Team.
