= Third-party software

The following files list, by DataStac Enterprise (DSE) version, the third-party software that is licensed for use with DSE.

== xref:3rdpartysoftware/dse68x.adoc[DataStax Enterprise 6.8.x third-party software]
Third-party software licensed for DataStax Enterprise 6.8.x.

== xref:3rdpartysoftware/dse67x.adoc[DataStax Enterprise 6.7.x third-party software]
Third-party software licensed for DataStax Enterprise 6.7.x.

== xref:3rdpartysoftware/dse60x.adoc[DataStax Enterprise 6.0.x third-party software]
Third-party software licensed for DataStax Enterprise 6.0.x.

== xref:3rdpartysoftware/dse51x.adoc[DataStax Enterprise 5.1.x third-party software]
Third-party software licensed for DataStax Enterprise 5.1.x.

== xref:3rdpartysoftware/opsc68x.adoc[DSE OpsCenter and DataStax Agent 6.8.x]
Third-party software licensed for DSE OpsCenter and DataStax Agent 6.8.x.

== xref:3rdpartysoftware/opsc67x.adoc[DSE OpsCenter and DataStax Agent 6.7.x]
Third-party software licensed for DSE OpsCenter and DataStax Agent 6.7.x.

== xref:3rdpartysoftware/opsc65x.adoc[DSE OpsCenter and DataStax Agent 6.5.x]
Third-party software licensed for DSE OpsCenter and DataStax Agent 6.5.x.

== xref:3rdpartysoftware/opsc61x.adoc[DSE OpsCenter and DataStax Agent 6.1.x]
Third-party software licensed for DSE OpsCenter and DataStax Agent 6.1.x.

== xref:3rdpartysoftware/studio.adoc[DataStax Studio]
Third-party software licensed for DataStax Studio 6.8.x.
