= Create your {astra_db} database
:slug: creating-your-astra-database

Complete the following steps to create and launch your {astra_db} database.

== Procedure

. In your https://astra.datastax.com/[{astra_db}] dashboard, select Create Database.
. If you don’t have an existing plan, select the free plan or a plan with annual savings. See xref:plan:plan-options.adoc[Plan options] for the benefits of each plan. You can upgrade from a pay as you go plan to a committed plan as your needs might change.
+
[NOTE]
If you need more options than the free or annual plan, contact {company} Support.

. If you creating a free plan, you don’t have to enter a credit card. You can get started for free with your $25 credit. You can enter a payment method later if needed.
If you are creating a database with annual savings, enter your payment method to continue.
. Enter your basic details:
** *Database Name:* Name your database something meaningful. The database name cannot be altered after the database is created. Use only alphanumeric characters; there is no character limit.
** *Keyspace Name:* Name your keyspace to reflect your data model. You can’t name your keyspace “dse” or “system”. Use only alphanumeric characters and no more than 48 total characters.
[arabic, start=4]
. Select your cloud provider and then the region where you want to launch your database from the region menu, which reflects the available regions based on your selected cloud provider.
+
[NOTE]
You can preview the costs for the database based on read and write requests, storage, and data transfer.

. Select Create Database.
. You will see a screen highlighting your selected plan. Select Continue.

=== Results

You are redirected to your Organization Dashboard. The new database and status is shown under Databases. +
You will receive an email when your database creation is complete. Select the database name to manage or connect with your new database.
