= Generate an authorization token
:slug: generate-auth-token-graphql

To authenticate with your http://astra.datastax.com[DataStax Astra database], generate an authentication token.
You'll use this token to authenticate with your database and make additional requests, such as creating tables or adding rows.

Use the link:_attachments/restv2.html#tag/createToken[authorization] endpoint to generate the token.
For the following examples, we'll use `cURL` commands.
If you're making requests from your application, use the code samples described in the authorization endpoint details.

[NOTE]
====
**Authorization token**
The authorization token is active for 30 minutes from the most recent request made.
If no request has been made within 30 minutes, the authorization token expires.
====

== Procedure
. Open a browser, navigate to https://astra.datastax.com/[DataStax Astra], and log in.
. From your *Dashboard* page, select your database
. Copy the **Cluster ID** of your database.
You can also find the **Cluster ID** in the URL, which is the last UUID in the path:
`https://astra.datastax.com/org/{org-Id}/database/{databaseid}`
. Add the **Cluster ID** as an environment variable with the following command:
+
[source, shell, subs="attributes+"]
----
export ASTRA_CLUSTER_ID={databaseid}
----
+
*Example*
+
[source, shell, subs="attributes+"]
----
export ASTRA_CLUSTER_ID=b5285f63-8da5-4c6e-afd8-ade371a48795
----

. Copy the *Region* of your database, the region where your database is located.
. Add the *Region* as an environment variable with the following command:
+
[source, shell, subs="attributes+"]
----
export ASTRA_CLUSTER_REGION={region}",
----
+
*Example*
+
[source, shell, subs="attributes+"]
----
export ASTRA_CLUSTER_REGION=us-east1
----
`
. Use `printenv` to ensure the environment variables were exported.
. Run the entire `cURL` command with the values for your database:

+
* Replace db_username with your *Client ID* from your xref:manage-tokens.adoc[application token].
* Replace db_password with your *Client Secret* from your xref:manage-tokens.adoc[application token].
+
[source, curl]
----
curl --request POST \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v1/auth \
  --header 'Content-Type: application/json' \
  --data '{"username":"'"$ASTRA_DB_USERNAME',"password":"'"$ASTRA_DB_PASSWORD"'"}'
----
+
* Optional: Add a unique UUID for the authorization request.
+
[TIP]
====
**Generating UUIDs**
Consider using a tool like this <a href="https://www.uuidgenerator.net/" target="_blank">Online UUID generator</a> to quickly create a random UUID to pass with your authorization request.
====
+
An authorization token is returned:
+
[source, curl]
----
{"authToken": "37396a44-dcb8-4740-a97f-79f0dba47973"}
----

. Copy the value of the returned `authToken` and store the authorization token in the `ASTRA_AUTHORIZATION_TOKEN` environment variable:
+
[source, shell, subs="attributes+"]
----
export ASTRA_AUTHORIZATION_TOKEN={authToken}
----
+
*Example*
+
[source, shell, subs="attributes+"]
----
export ASTRA_AUTHORIZATION_TOKEN=37396a44-dcb8-4740-a97f-79f0dba47973
----
The authorization token must be included when making requests to your database, such as creating tables, adding rows, or modifying columns.
Throughout the documentation examples, the authorization token is `37396a44-dcb8-4740-a97f-79f0dba47973`.

. If the authorization token expires, repeat steps 8 and 9 to store a new authorization token in the `ASTRA_AUTHORIZATION_TOKEN` environment variable.
