= Manage service account for your organization
:slug: manage-service-account

[IMPORTANT]
====
Only the Organization Administrator and Database Administrator, or xref:manage-custom-user-roles.adoc[custom roles], can 
====

== Create your service account

. Open a browser, navigate to link:https://astra.datastax.com[DataStax Astra], and log in.

[arabic, start=2]
. On the *Organization* page, select *Add Service Account*.

The *Service Account* information will be populated to show your *Client ID* and *Client Name*.

== Copying your service account secret


. Select the overflow menu for your service account.

. Select **Copy Credentials**.

[source, plaintext]
----
{
"clientId":"58391caa-5c48-4e28-8b70-da3fe1624f3c",
"clientName":"user@domain.com",
"clientSecret":"42d9e2h3-4d25-40k8-aa1a-c9f6cc73ef10"
}
----

Use your service account secret to
// xref:authenticating-your-service-account.adoc[Authenticate your service account] via the [DevOps API](ref:authentication-1).
authenticate.

== Refreshing your service account secret

If there are concerns that your service account has been compromised, you can refresh your client secret and update your API requests.

. Select the overflow menu for your service account.
. Select *Refresh Client Secret*.
. Confirm that you want to refresh your client secret, which will prevent any users from accessing the database API with the previous client secret.
. Select **Yes**.
