== Managing your database lifecycle
:slug: manage-database-with-service-account

Manage your databases with the DevOps API, which can be used to create, terminate, resize, park, and unpark your database. +

You can use the DevOps API to perform the actions which are available to you through your xref:manage:org/manage-permissions.adoc[role permissions].

The following roles can use the application token to use the DevOps API:

* Organization Administrator
* Database Administrator
* Custom roles with create, terminate, and expand database permissions

[NOTE]
====
If you were on a Free or {serverless} (Beta) tier before 4 March 2021, you were migrated to the pay as you go plan. You will need to reconnect to your database using your xref:manage:org/managing-org.adoc#_manage_application_tokens[application token].
====

Use the link:_attachments/devopsv2.html[DevOps API] to perform lifecycle actions for {company} {astra_db} databases.

. To use the DevOps API, create an xref:manage:org/managing-org.adoc#_manage_application_tokens[application token] to link:_attachments/devopsv2.html[authenticate your service account] in the DevOps API.
. Once you have authenticated your service account, you can create, terminate, resize, park, and unpark databases using the link:_attachments/devopsv2.html[DevOps API].

=== Example

[source,curl]
----
include::manage:example$devops/curl_get_available_regions.sh[]
----

[IMPORTANT]
====
You cannot resize, park, or unpark {serverless} databases. The commands will work with only {classic} databases.
====
