== Managing users

Use the DevOps API to create, modify, and delete users for your organization.

The following roles use the application token to execute DevOps API queries:

* Organization Administrator
* Database Administrator

=== Prerequisites

. Create an xref:manage:org/managing-org.adoc#_manage_application_tokens[application token] to link:_attachments/devopsv2.html[authenticate your service account] in the DevOps API.
. Once you have authenticated your service account, you can create and delete users in the link:_attachments/devopsv2.html[DevOps API].

=== Inviting a user

. Check existing users within the organization:
+
[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/curl_get_all_users.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::manage:example$results/devops_get_users.result[]
----
--
====

. Inviting a new user to your organization:
+
[source,shell, subs="attributes+"]
----
include::manage:example$devops/curl_invite_user.sh[]
----

For `roles`, use the `id` UUID value by xref:manage:devops/devops-api.adoc#_create_a_new_role[Getting existing roles in your organization]. The API results will show the UUID for each role `id`.

[NOTE]
====
Your invited user must validate their email address in their invitation before they can log in to Astra.
====

For more, see link:_attachments/devopsv2.html#operation/inviteUserToOrganization[Invite a user to an organization] in the DevOps API.

=== Getting user information

. Check for a specified user's information within the organization:
+
[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/curl_get_user.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::manage:example$results/devops_get_user.result[]
----
--
====

For more, see link:_attachments/devopsv2.html#operation/getOrganizationUser[Get an organization's user] in the DevOps API.

=== Removing a user

. Delete a user by their ID:
+
[source,shell, subs="attributes+"]
----
include::manage:example$devops/curl_delete_user.sh[]
----

. Confirm user no longer exists:
+
[tabs]
====
cURL command (/v2)::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/curl_get_user.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::manage:example$results/devops_get_deleted_user.result[]
----
--
====

For more, see link:_attachments/devopsv2.html#operation/removeUserFromOrganization[Remove or uninvite a user from an organization] in the DevOps API.

=== What's next?

Learn how to xref:manage:devops/devops-api.adoc#devops-tokens[manage tokens using the DevOps API].
