= Developing with the {database} Document API
:keywords: database, document, api

include::develop:partial$stargate-intro-intro.adoc[]
The Stargate Document API modifies and queries data stored as unstructured JSON documents in collections.
Because the Document API uses schemaless data, no data modeling is required!

If the Document API is used with Apache Cassandra, the document indexing is accomplished
with secondary indexes. 
If the Document API is used with DataStax Enterprise, SAI indexing is used. 
The blog https://stargate.io/2020/10/19/the-stargate-cassandra-documents-api.html[The Stargate Cassandra Documents API, window="_blank"] describes the underlying structure used to store collections.

== Information about namespaces and collections.

To use the Document API, you must define the namespace that will store  collections.
Collections store unstructured JSON documents.
Documents can themselves hold multiple documents.
Multiple collections are contained in a namespace, but a collection cannot be
contained in multiple namespaces.

Only namespaces need to be specifically created.
Collections are specified when a document is inserted.

== Prerequisites

include::develop:partial$prereqs-astra.adoc[]
include::develop:partial$prereqs-stargate.adoc[]

== API reference
If you prefer to learn using a QuickStart, try out the xref:quickstart:qs-document.adoc[Stargate Document QuickStart, window="_blank"].
To view the API Reference, see xref:develop:attachment$docv2.html[{database} Document API, window="_blank"].

// STARGATE ONLY
ifeval::["{product}" == "Stargate"]
include::develop:page$api-doc/doc-creating-namespace.adoc[Creating a namespace]
endif::[]

// ASTRA ONLY
ifeval::["{astra_generic}" == "Astra"]
=== Create namespace

See xref:manage:db/manage-keyspaces.adoc#adding-a-new-keyspace[Adding a new keyspace] to add a new namespace, or keyspace as it is known in Astra.
endif::[]

include::develop:page$api-doc/doc-checking-namespace.adoc[Checking for namespace]

// STARGATE ONLY
ifeval::["{product}" == "Stargate"]
include::develop:page$api-doc/doc-deleting-namespace.adoc[Dropping a namespace]
endif::[]

include::develop:page$api-doc/doc-writing-documents.adoc[Writing documents]

include::develop:page$api-doc/doc-reading-documents.adoc[Reading documents]

include::develop:page$api-doc/doc-updating-documents.adoc[Updating documents]

include::develop:page$api-doc/doc-deleting-documents.adoc[Deleting documents and collections]

== Document API Software Development Kit (SDK)

Node.js can be used with Astra to programmatically interact with your data using the Document API. An example of a client to work with collections is shown below:

include::develop:page$sdks/doc-nodejs-collection-client.adoc[Document API Node.js Collection Client, leveloffset=+2]
