= Downloading secure connect bundle
To connect to your {astra_db} database using the drivers, download the secure database bundle from the {company} {astra_db} console that contains the connection credentials.

. Open a browser, navigate to https://astra.datastax.com/[{astra_db}], and log in.

[arabic, start=2]
. From your *Dashboard* page, select your database.

[arabic, start=3]
. On the **Overview** page, select **Connect**.

[arabic, start=4]
. In the **Connect using a driver** section, click your preferred language from the list to load language-specific instructions.
+
include::ROOT:partial$note_multi-region_connect.adoc[]

Note, though, that the bundle URL is the same for all languages.

[arabic, start=5]
. Click **Download Bundle**.
+
[NOTE]
====
If you have multiple regions, you will have the option to download a bundle for each region from the expanded **Download Bundle** drop-down menu.
====

If you've enabled VPC peering, you can also **Download External Secure Connect Bundle** for use within your VPC peering.
The **secure-connect-*database_name*.zip** file downloads, which contains the security certificates and credentials for your database.

[NOTE]
====
VPC peering is only available on xref:manage:db/managing-db.adoc#classic-databases[Classic databases].
====

[TIP]
====
Alternatively, you can right-click the **Download credentials** link, copy the link source, and then use a `curl` command to download the **secure-connect-*database_name*.zip** file:

[source, shell, subs="attributes+"]
----
curl -L "<secure-connect-database_name-download-URL>" > database_name.zip
----
====

== Sharing secure connect bundle

Although teammates can access your {astra_db} database, it will not display in their list of available databases under *My Databases* in the {astra_db} console.

After you create an {astra_db} database, you can grant access to other members of your team by providing them with the database credentials and connection details for your database.

[WARNING]
====
Be careful when sharing connection details.
Providing this information to another user grants them access to your {astra_db} database and ownership capabilities, such as making modifications to the database.

For security, delete downloaded connection credentials after sending them to your teammate.
====
