= Manage multiple regions for your database
:slug: managing-regions

You can replicate data to multiple regions for high availability scenarios to ensure active-active applications failover models. Multiple regions also ensure application data availability for locality purposes with the added value of cost savings.

[NOTE]
====
Multiple regions are available on only xref:manage:db/managing-db.adoc#classic-databases[Classic databases] with a Production Workload databases.
====

== Adding a region to your database

. Open a browser, navigate to link:https://astra.datastax.com[DataStax Astra, window="_blank"], and log in.

[arabic,start=2]
. On the *Dashboard* page, select the database name to access the **Overview** page for your selected database.

[arabic,start=3]
. Select **Add Region**.

[arabic,start=4]
. Select the region you want to add from the **Add Region** menu.

[arabic,start=5]
. Select **Add**.

[arabic,start=6]
. Confirm you want to add the region by selecting **Confirm**.

You'll see a screen confirming the new datacenter region is being added.
Once you add a region, a maintenance period starts that might take up to 30 minutes.
Your database will have limited availability during this window.
Some actions, such as viewing database connection details, might be unavailable until maintenance is finished.

== Removing a region from your database

[arabic,start=1]
. Open a browser, navigate to link:https://astra.datastax.com[DataStax Astra, window="_blank"], and log in.

[arabic,start=2]
. On the *Dashboard* page, select the database name to access the **Overview** page for your selected database.

[arabic,start=3]
. Select **Remove Region** from the overflow menu for the region you want to remove.

[arabic,start=4]
. Enter your datacenter id, which is provided in the prompt.

[arabic,start=5]
. Select **Remove region**.

[CAUTION]
====
Removing a region is not reversible. Proceed with caution.
====

You'll see a screen confirming the datacenter location will be removed.
Once you remove a location, a maintenance period starts that might take up to 30 minutes.
Your database will have limited availability during this window.
Some actions, such as viewing database connection details, might be unavailable until maintenance is finished.
