= {company} Node.js driver
:slug: connecting-to-your-database-with-the-datastax-nodejs-driver
:page-tag: driver,dev,astra-db,connect

include::partial$driver-intro.adoc[Driver information]

== Prerequisites
* link:https://nodejs.org/en/download/)[Download, window="_blank"] and install a current Node.js LTS version with `npm`.

include::partial$app_client_id_secret.adoc[]

include::page$secure-connect-bundle.adoc[Secure connect bundle, leveloffset=+2]

== Connecting Node.js driver
. Install the {company} Node.js driver:
+
```
npm install cassandra-driver
```
. Create a `connect-database.js` file in the main directory for your Node.js project.
+
```
cd nodejsProject
touch connect-database.js
```
. Copy the following connection code into the `connect-database.js` file.
+
[NOTE]
====
Include the absolute path to the secure connect bundle for your Cassandra database (`secure-connect-database_name.zip`) in the `secureConnectBundle` parameter, as shown in the following examples.
====
+
```
'use strict'
const { Client } = require('cassandra-driver');
```
. After the `Client` class, add the following code to `connect-database.js`.
This code creates a `Client` instance to connect to your {astra_db} database, runs a CQL query, and prints the output to the console.

+
```
async function run() {
  const client = new Client({
    cloud: { secureConnectBundle: 'path/to/secure-connect-database_name.zip' },
    credentials: { username: 'clientId', password: 'clientSecret' }
  });

  await client.connect();

  // Execute a query
  const rs = await client.execute('SELECT * FROM system.local');
  console.log(`Hello from cluster: ${rs.first()['cluster_name']}`);

  await client.shutdown();
}

// Run the async function
run();
```

. Save and close the `connect-database.js` file.
. Run the `connect-database.js` example with the Node.js runtime:
+
```
node connect-database.js
```

The console output displays the _cluster_name_ value from the `system.local` table.

include::page$drivers/migrate-nodejs.adoc[Migrating your Node.js driver, leveloffset=+2]
