/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GcxFull {
        "templateScript": string;
    }
    interface GcxFullArticle {
        "html": HTMLElement;
        "lines": string;
        "name": string;
    }
    interface GcxFullCode {
        "html": string;
    }
}
declare global {
    interface HTMLGcxFullElement extends Components.GcxFull, HTMLStencilElement {
    }
    var HTMLGcxFullElement: {
        prototype: HTMLGcxFullElement;
        new (): HTMLGcxFullElement;
    };
    interface HTMLGcxFullArticleElement extends Components.GcxFullArticle, HTMLStencilElement {
    }
    var HTMLGcxFullArticleElement: {
        prototype: HTMLGcxFullArticleElement;
        new (): HTMLGcxFullArticleElement;
    };
    interface HTMLGcxFullCodeElement extends Components.GcxFullCode, HTMLStencilElement {
    }
    var HTMLGcxFullCodeElement: {
        prototype: HTMLGcxFullCodeElement;
        new (): HTMLGcxFullCodeElement;
    };
    interface HTMLElementTagNameMap {
        "gcx-full": HTMLGcxFullElement;
        "gcx-full-article": HTMLGcxFullArticleElement;
        "gcx-full-code": HTMLGcxFullCodeElement;
    }
}
declare namespace LocalJSX {
    interface GcxFull {
        "onLinesSelected"?: (event: CustomEvent<any>) => void;
        "templateScript"?: string;
    }
    interface GcxFullArticle {
        "html"?: HTMLElement;
        "lines"?: string;
        "name"?: string;
    }
    interface GcxFullCode {
        "html"?: string;
    }
    interface IntrinsicElements {
        "gcx-full": GcxFull;
        "gcx-full-article": GcxFullArticle;
        "gcx-full-code": GcxFullCode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcx-full": LocalJSX.GcxFull & JSXBase.HTMLAttributes<HTMLGcxFullElement>;
            "gcx-full-article": LocalJSX.GcxFullArticle & JSXBase.HTMLAttributes<HTMLGcxFullArticleElement>;
            "gcx-full-code": LocalJSX.GcxFullCode & JSXBase.HTMLAttributes<HTMLGcxFullCodeElement>;
        }
    }
}
