= Authenticating {classic} databases

include::ROOT:partial$note_classic_only.adoc[]

{classic_cap} databases were created before 4 March 2021. These databases have fixed compute and storage capabilities and do not include the latest authentication version.

To authenticate your {company} {astra_db} {classic} database, generate an authorization token. You'll use this token to authenticate with your database and make additional requests, such as creating tables or adding rows.

Use the link:_attachments/restv2.html#operation/createToken[authorization] endpoint to generate the token. For the following examples, we'll use `cURL` commands. If you're making requests from your application, use the code samples described in the authorization endpoint details.


[NOTE]
====
The authorization token is active for 30 minutes from the most recent request made. If no request has been made within 30 minutes, the authorization token expires.
====

. Open a browser, navigate to link:https://astra.datastax.com/[{astra_db}], and log in.
. From your **Dashboard** page, select your database.
. Copy the **Cluster ID** of your database. You can also find the **Cluster ID** in the URL, which is the last UUID in the path: `https://astra.datastax.com/org/{org-Id}/database/{databaseid}`
. Add the **Cluster ID** as an environment variable with the following command:


[tabs]
====
Set environment variable::
+
--
[source,shell, subs="attributes+"]
----
export ASTRA_CLUSTER_ID={databaseid}
----
--

Example::
+
--
[source,plaintext]
----
export ASTRA_CLUSTER_ID=b5285f63-8da5-4c6e-afd8-ade371a48795
----
--
====


[arabic, start=5]
. Copy the **Region** of your database, the region where your database is located.
. Add the **Region** as an environment variable with the following command:

[tabs]
====
Set environment variable::
+
--
[source,shell, subs="attributes+"]
----
export ASTRA_CLUSTER_REGION={region}
----
--

Example::
+
--
[source,plaintext]
----
export ASTRA_CLUSTER_REGION=us-east1
----
--
====


[arabic, start=7]
. Add your username, keyspace, and your password as environment variables with the following command:

[tabs]
====
Set environment variable::
+
--
[source,shell, subs="attributes+"]
----
export ASTRA_DB_USERNAME={username}
export ASTRA_DB_KEYSPACE={keyspace}
export ASTRA_DB_PASSWORD={password}
----
--

Example::
+
--
[source,plaintext]
----
export ASTRA_DB_USERNAME=john.smith@datastax.com
export ASTRA_DB_KEYSPACE=users
export ASTRA_DB_PASSWORD=P@ssw0rd
----
--
====


[arabic, start=8]
. Use `printenv` to ensure the environment variables were exported.
. Run the entire `cURL` command with the values for your database:
  * Replace `db_username` with your database username.
  * Replace `db_password` with your database password.
  * Optional: Add a unique UUID for the authorization request:

[source,cURL]
----
curl --request POST \\
 --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v1/auth \
 --header 'Content-Type: application/json' \
 --data '{"username":"'"$ASTRA_DB_USERNAME"'", "password":"'"$ASTRA_DB_PASSWORD"'"}'
 --header 'x-cassandra-request-id: {unique-UUID}
----

[NOTE]
====
Consider using a tool like this link:https://www.uuidgenerator.net/[Online UUID generator, window="_blank"] to quickly create a random UUID to pass with your authorization request.
====

An authorization token is returned:
[source,plaintext]
----
{"authToken": "37396a44-dcb8-4740-a97f-79f0dba47973"}
----

[arabic, start=10]
. Copy the value of the returned `authToken` and store the authorization token in the `ASTRA_AUTHORIZATION_TOKEN` environment variable:

[tabs]
====
Set environment variable::
+
--
[source,shell, subs="attributes+"]
----
export ASTRA_AUTHORIZATION_TOKEN={authToken}
----
--

Example::
+
--
[source,plaintext]
----
export ASTRA_AUTHORIZATION_TOKEN=37396a44-dcb8-4740-a97f-79f0dba47973
----
--
====

The authorization token must be included when making requests to your database, such as creating tables, adding rows, or modifying columns.

[arabic, start=11]
. If the authorization token expires, generate a new authorization token and update it in the `ASTRA_AUTHORIZATION_TOKEN` environment variable.

== What's next?
include::ROOT:partial$app_token_next_steps.adoc[]
