site:
  title: DataStax Astra Documentation
  url: https://docs.datastax.com/en/astra/docs
  keys:
    segmentIo: d24gQtyKIUu5mLdkp11xjfiXLhRqx0HH
 
content:
  edit_url: ~
  sources:
  - url: .
    branches: HEAD

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/raw/main/releases/download/v0.8/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
  output_dir: assets

asciidoc:
  attributes:
    source-highlighter: highlightjs
    page-pagination: ''
  extensions:
  - ./lib/tabs-block.js
