== {astra_db} plan options

=== Serverless databases

{company} {astra_db} offers a serverless database, which is an elastic cloud-native database that scales with your workload. You can scale your compute and storage capabilities independently, allowing you to focus on developing your application and less on your infrastructure costs.

[IMPORTANT]
====
On 4 March 2021, all Free, Serverless (Beta), and Dev and Test databases were migrated to the serverless free plan with a $25 monthly credit that is refreshed monthly. +
{astra_db} offers two plans in the {astra_db} console: free and annual commitment. Each of these plans are billed according to {astra_db} pricing, which is based on read and write requests, data storage, and data transfer. If you need more options than the free or annual plan, contact a mailto:bdr@datastax.com[{company} Business Development Representative].
====

==== Limitations

Serverless databases don't support VPC peering or materialized views. Our team is working to offer these feature for serverless databases soon.


=== Classic database options

include::ROOT:partial$note_classic_only.adoc[]

[IMPORTANT]
====
Classic databases can no longer be created through the {astra_db} console. We recommend migrating your database to our current serverless option, which could save you money and allow you to manage your compute and storage capabilities separately.
====

==== Dev and Test with Shared Resources

Dev and Test databases offer an entry point for developers. Only select AWS and Google Cloud regions are available for the Dev and Test databases. Dev and Test databases don't support VPC peering or multi-region databases.
|===
|*Plan*|*Description*

|A5|3 vCPU, 12GB DRAM, 10GB total usable storage
|A10|6 vCPU, 24GB DRAM, 20GB total usable storage
|A20|12 vCPU, 48GB DRAM, 40GB total usable storage
|A40|24 vCPU, 96GB DRAM, 80GB total usable storage
|===

==== Production Workloads with Dedicated Resources

VPC peering and multi-region databases are available on Production Workload databases.
|===
|*Plan*|*Description*

|C10|12 vCPU, 48GB DRAM, 500GB total usable storage
|C20|24 vCPU, 96GB DRAM, 500GB total usable storage
|C30|48 vCPU, 192GB DRAM, 500GB total usable storage
|===

==== High-Density Production Workloads with Dedicated Resources

High-Density Production Workload databases offer greater disk capacity and performance than other service tiers. VPC peering and multi-region databases are available on High-Density Product Workload databases.
|===
|*Plan*|*Description*
|D10|12 vCPU, 48GB DRAM, 1500GB total usable storage
|D20|24 vCPU, 96GB DRAM, 1500GB total usable storage
|D40|48 vCPU, 192GB DRAM, 1500GB total usable storage
|===
