/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GcxSchema {
    }
    interface GcxSchemaBottomSidebar {
        "language": string;
        "uri": any;
    }
    interface GcxSchemaSampleAppGallery {
        "language": string;
        "uri": any;
    }
    interface GcxSchemaTopbar {
        "language": string;
        "uri": any;
    }
}
declare global {
    interface HTMLGcxSchemaElement extends Components.GcxSchema, HTMLStencilElement {
    }
    var HTMLGcxSchemaElement: {
        prototype: HTMLGcxSchemaElement;
        new (): HTMLGcxSchemaElement;
    };
    interface HTMLGcxSchemaBottomSidebarElement extends Components.GcxSchemaBottomSidebar, HTMLStencilElement {
    }
    var HTMLGcxSchemaBottomSidebarElement: {
        prototype: HTMLGcxSchemaBottomSidebarElement;
        new (): HTMLGcxSchemaBottomSidebarElement;
    };
    interface HTMLGcxSchemaSampleAppGalleryElement extends Components.GcxSchemaSampleAppGallery, HTMLStencilElement {
    }
    var HTMLGcxSchemaSampleAppGalleryElement: {
        prototype: HTMLGcxSchemaSampleAppGalleryElement;
        new (): HTMLGcxSchemaSampleAppGalleryElement;
    };
    interface HTMLGcxSchemaTopbarElement extends Components.GcxSchemaTopbar, HTMLStencilElement {
    }
    var HTMLGcxSchemaTopbarElement: {
        prototype: HTMLGcxSchemaTopbarElement;
        new (): HTMLGcxSchemaTopbarElement;
    };
    interface HTMLElementTagNameMap {
        "gcx-schema": HTMLGcxSchemaElement;
        "gcx-schema-bottom-sidebar": HTMLGcxSchemaBottomSidebarElement;
        "gcx-schema-sample-app-gallery": HTMLGcxSchemaSampleAppGalleryElement;
        "gcx-schema-topbar": HTMLGcxSchemaTopbarElement;
    }
}
declare namespace LocalJSX {
    interface GcxSchema {
    }
    interface GcxSchemaBottomSidebar {
        "language"?: string;
        "uri"?: any;
    }
    interface GcxSchemaSampleAppGallery {
        "language"?: string;
        "uri"?: any;
    }
    interface GcxSchemaTopbar {
        "language"?: string;
        "uri"?: any;
    }
    interface IntrinsicElements {
        "gcx-schema": GcxSchema;
        "gcx-schema-bottom-sidebar": GcxSchemaBottomSidebar;
        "gcx-schema-sample-app-gallery": GcxSchemaSampleAppGallery;
        "gcx-schema-topbar": GcxSchemaTopbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcx-schema": LocalJSX.GcxSchema & JSXBase.HTMLAttributes<HTMLGcxSchemaElement>;
            "gcx-schema-bottom-sidebar": LocalJSX.GcxSchemaBottomSidebar & JSXBase.HTMLAttributes<HTMLGcxSchemaBottomSidebarElement>;
            "gcx-schema-sample-app-gallery": LocalJSX.GcxSchemaSampleAppGallery & JSXBase.HTMLAttributes<HTMLGcxSchemaSampleAppGalleryElement>;
            "gcx-schema-topbar": LocalJSX.GcxSchemaTopbar & JSXBase.HTMLAttributes<HTMLGcxSchemaTopbarElement>;
        }
    }
}
