== Get private endpoints information with the DevOps API

Use the DevOps API to create, remove, and manage private endpoints.

You can use the DevOps API to perform the actions your xref:manage:org/managing-org.adoc#_manage_user_permissions[role permissions] allow.

include::ROOT:partial$endpoint_perm.adoc[]

=== Prerequisites

Ensure you have xref:manage:org/managing-org.adoc#_manage_user_permissions[permission] to manage private endpoints.

[NOTE]
====
To increase your security, consider xref:manage:db/manage-access-list.adoc[restricting public access] to your database using the access list.
====

=== Get a list of private endpoint configurations

. Check existing private endpoint configurations within your organization or database:

+
[tabs]
====
cURL command (/v2): Get all private endpoints in organization::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/private_endpoint/curl_get_private_endpoints_org.sh[]
----
--

cURL command (/v2): Get all private endpoints in database::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/private_endpoint/curl_get_private_endpoints_db.sh[]
----
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::manage:example$results/private_endpoint/devops_get_private_endpoints_aws.result[]
----
--
====


=== Get a list of private endpoint connections

. Check existing private endpoint connections within your organization or database:

+
[tabs]
====
cURL command (/v2): Get all private endpoint connections in organization::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/private_endpoint/curl_get_private_endpoint_connections_org.sh[]
----
--

cURL command (/v2): Get all private endpoint connections in database::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/private_endpoint/curl_get_private_endpoint_connections_db.sh[]
----
--

cURL command (/v2): Get all private endpoint connections in specified region::
+
--
[source,shell, subs="attributes+"]
----
include::manage:example$devops/private_endpoint/curl_get_private_endpoint_connections_region.sh[]
----

If the database is only in a single region, `datacenterID` is your `databaseID`.
--

Result::
+
--
[source,plaintext, subs="attributes+"]
----
include::manage:example$results/private_endpoint/devops_get_private_endpoint_connections_aws.result[]
----
--
====

=== What's next?

Learn how to connect to xref:db-devops-aws-private-endpoints.adoc[AWS PrivateLink], xref:db-devops-azure-private-endpoints.adoc[Azure Private Link], or xref:db-devops-gcp-private-endpoints.adoc[Google Cloud Private Service Connect].

Explore link:_attachments/devopsv2.html#operation/Private-Endpoints[Private endpoints] in the DevOps API.
